// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Desktop: typeof import('./src/components/navbar/desktop.vue')['default']
    Footer: typeof import('./src/components/footer/footer.vue')['default']
    FooterCol: typeof import('./src/components/footer/footerCol.vue')['default']
    FooterFollow: typeof import('./src/components/footer/footerFollow.vue')['default']
    Mobile: typeof import('./src/components/navbar/mobile.vue')['default']
    Navbar: typeof import('./src/components/navbar/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WIP: typeof import('./src/components/WIP.vue')['default']
  }
}
