// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    FooterCol: typeof import('./src/components/footer/FooterCol.vue')['default']
    FooterFollow: typeof import('./src/components/footer/FooterFollow.vue')['default']
    FooterIcon: typeof import('./src/components/footer/FooterIcon.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
