// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Desktop: typeof import('./src/components/navbar/desktop.vue')['default']
    Mobile: typeof import('./src/components/navbar/mobile.vue')['default']
    Navbar: typeof import('./src/components/navbar/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
